Update ClspvReflection non-semantic instruction set
KhronosGroup/SPIRV-Headers pull request #308
Opened 2022-12-08 17:24 UTC by callumfare

Add support to the clspv reflection non-semantic instruction set for:
* Printf builtin
* Device address push constants for module-scope constants and program-scope global variables

This contribution is being made by Codeplay on behalf of Samsung.

2022-12-14 21:05 UTC, alan-baker requested changes
This will also need regenerated based on the resolution of https://github.com/KhronosGroup/SPIRV-Registry/pull/178

2022-12-14 21:05 UTC, alan-baker commented on include/spirv/unified1/extinst.nonsemantic.clspvreflection.grammar.json
> +          "enumerant" : "FlagMayUsePrintf",
```suggestion
          "enumerant" : "MayUsePrintf",
```

2022-12-15 16:25 UTC, alan-baker commented on include/spirv/unified1/extinst.nonsemantic.clspvreflection.grammar.json
> +        { "kind" : "IdRef", "name" : "Flags", "quantifier" : "?" }
This is not listed as optional in the instruction set I think.

2022-12-16 19:29 UTC, alan-baker requested changes

2022-12-16 19:29 UTC, alan-baker commented on include/spirv/unified1/extinst.nonsemantic.clspvreflection.grammar.json
> +        { "kind" : "IdRef", "name" : "Flags" }
Sorry there was a disconnect between the two reviews. These should both be optional for backwards compatibility. The validation for this instruction should eventually be updated to reject this instruction of the number of operands is not 2 in version 4 and 4 in version 5.

2022-12-16 19:29 UTC, alan-baker commented on include/spirv/unified1/extinst.nonsemantic.clspvreflection.grammar.json
> +        { "kind" : "IdRef", "name" : "Flags" }
I think the statement about the missing operands in the instruction set covers the optionality aspect in the spec language enough.

2022-12-22 11:24 UTC, callumfare commented
I've addressed the review feedback. I've also added a change from @FMarno which adds another operand to support clGetKernelInfo with `CL_KERNEL_ATTRIBUTES`

2023-01-03 14:46 UTC, merged