Add SPV_AMDX_shader_enqueue
KhronosGroup/SPIRV-Headers pull request #366
Opened 2023-07-29 19:56 UTC by KonstantinSeurer

Based on https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_AMDX_shader_enqueue.adoc .

2023-07-29 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Headers?pullRequest=366) it.</sub>

2023-08-01 15:57 UTC, yavn requested changes
Hi @KonstantinSeurer, thank you for the PR! We should have pushed it out with the release, but it was overlooked. Looks good, just a few minor corrections.

2023-08-01 15:57 UTC, yavn commented on include/spirv/unified1/spirv.core.grammar.json
> +          "capabilities" : [ "ShaderEnqueueAMDX" ],
```suggestion
          "capabilities" : [ "Shader" ],
```

2023-08-01 16:01 UTC, yavn commented
NB: For practical use in shaders, the following SPIR-V intrinsics helpers are provided:

- [shaderEnqueueSpirvIntrinsics.glsl.h](https://github.com/GPUOpen-LibrariesAndSDKs/Vulkan-Samples/blob/main/shaders/gpu_dispatch/glsl/shaderEnqueueSpirvIntrinsics.glsl.h)
- [shaderEnqueueSpirvIntrinsics.hlsl.h](https://github.com/GPUOpen-LibrariesAndSDKs/Vulkan-Samples/blob/main/shaders/gpu_dispatch/hlsl/shaderEnqueueSpirvIntrinsics.hlsl.h)

2023-08-01 16:16 UTC, yavn approved these changes

2023-08-02 14:39 UTC, johnkslang commented
Why does this show a force pushes to main?

2023-08-02 14:43 UTC, KonstantinSeurer commented
> Why does this show a force pushes to main?

Because I force pushed fixups to my main branch (https://github.com/KonstantinSeurer/SPIRV-Headers/commits/main)

2023-08-02 14:53 UTC, johnkslang commented
Okay, thanks.

2023-08-02 15:38 UTC, alan-baker requested changes

2023-08-02 15:38 UTC, alan-baker commented on include/spirv/unified1/spirv.core.grammar.json
> +      "extensions" : [ "SPV_AMDX_shader_enqueue" ],
Only capabilities introduced by the extension should be enabled by extensions. Instructions and other enumerants should only be enabled by capability.

2023-08-09 14:01 UTC, KonstantinSeurer commented
Is there anything else that needs to be done for merging this PR? I'd like to land it before https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24512 .

2023-08-10 12:06 UTC, yavn approved these changes
Thanks, looks good for me. Not sure who can help merge it now.

2023-08-10 20:29 UTC, bashbaug approved these changes
LGTM, this has a few approvals now so I'll just merge it.

2023-08-10 20:31 UTC, merged