Add a Source Language for Zig
KhronosGroup/SPIRV-Headers pull request #403
Opened 2024-01-14 00:06 UTC by Snektron

Adds source language identifiers for [Zig](https://ziglang.org/) (github: [ziglang/zig](https://github.com/ziglang/zig)). The self-hosted Zig has a work-in-progress SPIR-V backend.

2024-01-14 00:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=403) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=403) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Headers?pullRequest=403) it.</sub>

2024-01-16 22:55 UTC, alan-baker requested changes

2024-01-16 22:55 UTC, alan-baker commented on include/spirv/unified1/spirv.core.grammar.json
> +          "version" : "1.0",
One of the builds complains about the next line. I assume because of this trailing comma.

2024-01-17 00:19 UTC, alan-baker approved these changes

2024-01-17 16:46 UTC, bashbaug commented
Merging as discussed in the January 17th teleconference.

2024-01-17 16:46 UTC, merged