Add scope resolution operator in spirv.hpp11
KhronosGroup/SPIRV-Headers pull request #456
Opened 2024-10-16 22:49 UTC by Christian-Conti

The file spirv.hpp11 was missing of the scope resolution operator :: in the cases insde the funcions to separate the namespace from the member

2024-10-16 22:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=456) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Headers?pullRequest=456) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Headers?pullRequest=456) it.</sub>

2024-10-17 10:52 UTC, Naghasan requested changes
Hi,
Thanks for your contribution,

The headers are generated by tools not maintained by hand. The process here would be to fix the generator, regenerate the headers and commit all the changes.

In this case I think the issue comes from here
https://github.com/KhronosGroup/SPIRV-Headers/pull/426/files#diff-6b795ceb0e0e4f975be731d875f1df04b8f13003934cb2b2086e78e7c6b10f12R583

2024-10-17 11:04 UTC, Christian-Conti commented
Hi,
Thank you for your reply. Yes, the issue seems to be in those lines. I cloned your with a script during the make process, and I missed the generation script. I found it simpler to add the operator by hand, but I will try to fix the generator itself.
Christian

________________________________
Da: Victor Lomuller ***@***.***>
Inviato: giovedì 17 ottobre 2024 12:53
A: KhronosGroup/SPIRV-Headers ***@***.***>
Cc: Christian Conti ***@***.***>; Author ***@***.***>
Oggetto: Re: [KhronosGroup/SPIRV-Headers] Add scope resolution operator in spirv.hpp11 (PR #456)


@Naghasan requested changes on this pull request.

Hi,
Thanks for your contribution,

The headers are generated by tools not maintained by hand. The process here would be to fix the generator, regenerate the headers and commit all the changes.

In this case I think the issue comes from here
https://github.com/KhronosGroup/SPIRV-Headers/pull/426/files#diff-6b795ceb0e0e4f975be731d875f1df04b8f13003934cb2b2086e78e7c6b10f12R583

—
Reply to this email directly, view it on GitHub<https://github.com/KhronosGroup/SPIRV-Headers/pull/456#pullrequestreview-2374862081>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3ZZJZSZ4VZDKVGVEVUTP73Z36JJZAVCNFSM6AAAAABQCPDXM6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZUHA3DEMBYGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-29 14:34 UTC, Naghasan commented
closing in favour of https://github.com/KhronosGroup/SPIRV-Headers/pull/463

2024-10-29 14:34 UTC, closed without merging